name: Deploy Testing Database Changes

on:
#  push:
  workflow_dispatch:

jobs:
  deploy-database-changes:
    runs-on: ubuntu-latest
    container:
      image: liquibase/liquibase:latest
      env:
        LIQUIBASE_PRO_LICENSE_KEY:  ${{ secrets.PRO_KEY }}
        LIQUIBASE_LAUNCH_DARKLY_SDK_KEY: ${{ secrets.LAUNCHDARKLY_SDK_DEV_KEY }}
        LIQUIBASE_VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        LIQUIBASE_VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        LIQUIBASE_COMMAND_URL: "hashicorp,admin/kv/demo-dev-url,url"
        LIQUIBASE_COMMAND_USERNAME: "hashicorp,admin/kv/demo-dev-username,username"
        LIQUIBASE_COMMAND_PASSWORD: "hashicorp,admin/kv/demo-dev-password,password"
        LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelogs/changes.yml"
        LIQUIBASE_COMMAND_DRIVER: "org.postgresql.Driver"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: lpm update && lpm add launchdarkly hashicorp-vault

      - name: Update
        run: liquibase update --log-level SEVERE
