name: Deploy Testing Database Changes

on:
  push:
  workflow_dispatch:

jobs:
  deploy-database-changes:
    runs-on: ubuntu-latest
    container:
      image: liquibase/liquibase:latest
      env:
        LIQUIBASE_PRO_LICENSE_KEY:  ${{ secrets.PRO_KEY }}
        LIQUIBASE_URL:  ${{ secrets.DEMO_TEST_URL }}
        LIQUIBASE_USERNAME:  ${{ secrets.DEMO_TEST_USERNAME }}
        LIQUIBASE_PASSWORD:  ${{ secrets.DEMO_TEST_PASSWORD }}
        LIQUIBASE_CHANGELOG_FILE: "changelogs/changes.yml"
        LIQUIBASE_DRIVER: "org.postgresql.Driver"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: ls

      - name: Verify
        run: liquibase verify
